export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as Clients } from './Clients'
export { default as Testimonials } from './Testimonials'
export { default as Contact } from './Contact'
export { default as Header } from './Header'
